/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softcons.jframetest;
import softcons.jframetest.NewJFrame;
/**
 *
 * @author ibrah
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        donutchk = new javax.swing.JCheckBox();
        pastrychk = new javax.swing.JCheckBox();
        lattechk = new javax.swing.JCheckBox();
        cappucinochk = new javax.swing.JCheckBox();
        puddingchk = new javax.swing.JCheckBox();
        muffinchk = new javax.swing.JCheckBox();
        brownieschk = new javax.swing.JCheckBox();
        coldcoffeechk = new javax.swing.JCheckBox();
        icecreamchk = new javax.swing.JCheckBox();
        cakeschk = new javax.swing.JCheckBox();
        donutqty = new javax.swing.JTextField();
        pastryqty = new javax.swing.JTextField();
        latteqty = new javax.swing.JTextField();
        cappucinoqty = new javax.swing.JTextField();
        puddingqty = new javax.swing.JTextField();
        muffinqty = new javax.swing.JTextField();
        browniesqty = new javax.swing.JTextField();
        coldcoffeeqty = new javax.swing.JTextField();
        icecreamqty = new javax.swing.JTextField();
        cakesqty = new javax.swing.JTextField();
        orderbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Menu");

        jLabel2.setText("Item");

        jLabel3.setText("Qty");

        donutchk.setText("donuts");
        donutchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donutchkActionPerformed(evt);
            }
        });

        pastrychk.setText("pastry");
        pastrychk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastrychkActionPerformed(evt);
            }
        });

        lattechk.setText("latte");
        lattechk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lattechkActionPerformed(evt);
            }
        });

        cappucinochk.setText("cappucino");
        cappucinochk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappucinochkActionPerformed(evt);
            }
        });

        puddingchk.setText("pudding");
        puddingchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puddingchkActionPerformed(evt);
            }
        });

        muffinchk.setText("muffin");
        muffinchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muffinchkActionPerformed(evt);
            }
        });

        brownieschk.setText("brownies");
        brownieschk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownieschkActionPerformed(evt);
            }
        });

        coldcoffeechk.setText("cold coffee");
        coldcoffeechk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldcoffeechkActionPerformed(evt);
            }
        });

        icecreamchk.setText("ice cream");
        icecreamchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecreamchkActionPerformed(evt);
            }
        });

        cakeschk.setText("cakes");
        cakeschk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cakeschkActionPerformed(evt);
            }
        });

        browniesqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browniesqtyActionPerformed(evt);
            }
        });

        orderbtn.setText("Place Order");
        orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cakeschk)
                                    .addComponent(icecreamchk)
                                    .addComponent(coldcoffeechk)
                                    .addComponent(brownieschk)
                                    .addComponent(muffinchk)
                                    .addComponent(puddingchk)
                                    .addComponent(cappucinochk)
                                    .addComponent(lattechk)
                                    .addComponent(pastrychk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2)
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(latteqty)
                                            .addComponent(cappucinoqty)
                                            .addComponent(puddingqty)
                                            .addComponent(muffinqty)
                                            .addComponent(browniesqty)
                                            .addComponent(coldcoffeeqty)
                                            .addComponent(icecreamqty)
                                            .addComponent(cakesqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(donutchk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(donutqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pastryqty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(orderbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(donutchk)
                            .addComponent(donutqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pastrychk))
                    .addComponent(pastryqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lattechk)
                    .addComponent(latteqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappucinochk)
                    .addComponent(cappucinoqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puddingchk)
                    .addComponent(puddingqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muffinchk)
                    .addComponent(muffinqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brownieschk)
                    .addComponent(browniesqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coldcoffeechk)
                    .addComponent(coldcoffeeqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icecreamchk)
                    .addComponent(icecreamqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cakeschk)
                    .addComponent(cakesqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderbtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browniesqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browniesqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browniesqtyActionPerformed

    private void donutchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutchkActionPerformed
        if(!donutchk.isSelected())
        {
            donutqty.setText(null);
        }
    }//GEN-LAST:event_donutchkActionPerformed

    private void orderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbtnActionPerformed
        if (donutchk.isSelected()&&!donutqty.getText().equals("") && !donutqty.getText().equals("0"))
        {
            NewJFrame.order.add(donutchk.getText());
            NewJFrame.quantity.add(donutqty.getText());
//            System.out.println(donutchk.getText());
        }
        
        if ( pastrychk.isSelected() && !pastryqty.getText().equals("") && !pastryqty.getText().equals("0"))
        {
            NewJFrame.order.add( pastrychk.getText());
            NewJFrame.quantity.add( pastryqty.getText());
        }
        
        if ( lattechk.isSelected() && !latteqty.getText().equals("") && !latteqty.getText().equals("0"))
        {
            NewJFrame.order.add( lattechk.getText());
            NewJFrame.quantity.add( latteqty.getText());
        }
        
        if ( cappucinochk.isSelected() && !cappucinoqty.getText().equals("") && !cappucinoqty.getText().equals("0"))
        {
            NewJFrame.order.add( cappucinochk.getText());
            NewJFrame.quantity.add( cappucinoqty.getText());
        }
        
        if ( puddingchk.isSelected() && !puddingqty.getText().equals("") && !puddingqty.getText().equals("0"))
        {
            NewJFrame.order.add( puddingchk.getText());
            NewJFrame.quantity.add( puddingqty.getText());
        }
        
        if ( muffinchk.isSelected() && !muffinqty.getText().equals("") && !muffinqty.getText().equals("0"))
        {
            NewJFrame.order.add( muffinchk.getText());
            NewJFrame.quantity.add( muffinqty.getText());
        }
        
        if ( brownieschk.isSelected() && !browniesqty.getText().equals("") && !browniesqty.getText().equals("0"))
        {
            NewJFrame.order.add( brownieschk.getText());
            NewJFrame.quantity.add( browniesqty.getText());
        }
        
        if ( coldcoffeechk.isSelected() && !coldcoffeeqty.getText().equals("") && !coldcoffeeqty.getText().equals("0"))
        {
            NewJFrame.order.add( coldcoffeechk.getText());
            NewJFrame.quantity.add( coldcoffeeqty.getText());
        }
        
        if ( icecreamchk.isSelected() && !icecreamqty.getText().equals("") && !icecreamqty.getText().equals("0"))
        {
            NewJFrame.order.add( icecreamchk.getText());
            NewJFrame.quantity.add( icecreamqty.getText());
        }
        
        if ( cakeschk.isSelected() && !cakesqty.getText().equals("") && !cakesqty.getText().equals("0"))
        {
            NewJFrame.order.add( cakeschk.getText());
            NewJFrame.quantity.add( cakesqty.getText());
        }
//        System.out.println(NewJFrame.order);
//        System.out.println(NewJFrame.quantity);
        dispose();
        employeelogin log = new employeelogin();
        log.setVisible(true);
    }//GEN-LAST:event_orderbtnActionPerformed

    private void pastrychkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastrychkActionPerformed
        if (!pastrychk.isSelected()){
            pastryqty.setText(null);
        }
    }//GEN-LAST:event_pastrychkActionPerformed

    private void lattechkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lattechkActionPerformed
        if(!lattechk.isSelected()){
            latteqty.setText(null);
        }
    }//GEN-LAST:event_lattechkActionPerformed

    private void cappucinochkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappucinochkActionPerformed
        if(!cappucinochk.isSelected()){
            cappucinoqty.setText(null);
        }
    }//GEN-LAST:event_cappucinochkActionPerformed

    private void puddingchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puddingchkActionPerformed
        if(!puddingchk.isSelected()){
            puddingqty.setText(null);
        }
    }//GEN-LAST:event_puddingchkActionPerformed

    private void muffinchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muffinchkActionPerformed
        if(!muffinchk.isSelected()){
            muffinqty.setText(null);
        }
    }//GEN-LAST:event_muffinchkActionPerformed

    private void brownieschkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownieschkActionPerformed
        if(!brownieschk.isSelected()){
            browniesqty.setText(null);
        }
    }//GEN-LAST:event_brownieschkActionPerformed

    private void coldcoffeechkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldcoffeechkActionPerformed
        if (!coldcoffeechk.isSelected()){
            coldcoffeeqty.setText(null);
        }
    }//GEN-LAST:event_coldcoffeechkActionPerformed

    private void icecreamchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecreamchkActionPerformed
        if(!icecreamchk.isSelected()){
            icecreamqty.setText(null);
        }
    }//GEN-LAST:event_icecreamchkActionPerformed

    private void cakeschkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cakeschkActionPerformed
        if (!cakeschk.isSelected())
        {
            cakesqty.setText(null);
        }
    }//GEN-LAST:event_cakeschkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox brownieschk;
    private javax.swing.JTextField browniesqty;
    private javax.swing.JCheckBox cakeschk;
    private javax.swing.JTextField cakesqty;
    private javax.swing.JCheckBox cappucinochk;
    private javax.swing.JTextField cappucinoqty;
    private javax.swing.JCheckBox coldcoffeechk;
    private javax.swing.JTextField coldcoffeeqty;
    private javax.swing.JCheckBox donutchk;
    private javax.swing.JTextField donutqty;
    private javax.swing.JCheckBox icecreamchk;
    private javax.swing.JTextField icecreamqty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox lattechk;
    private javax.swing.JTextField latteqty;
    private javax.swing.JCheckBox muffinchk;
    private javax.swing.JTextField muffinqty;
    private javax.swing.JButton orderbtn;
    private javax.swing.JCheckBox pastrychk;
    private javax.swing.JTextField pastryqty;
    private javax.swing.JCheckBox puddingchk;
    private javax.swing.JTextField puddingqty;
    // End of variables declaration//GEN-END:variables
}
