/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softcons.jframetest;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import org.lightcouch.Response;

/**
 *
 * @author ibrah
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    static int temp=0;
    static int count,count1,count2,count3;
    static String dc ,bc ;
    public Employee() {
        initComponents();
        cname.setText(NewJFrame.myusername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        confirmbt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Employee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name");

        cname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        confirmbt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmbt.setText("Confirm Order for this customer");
        confirmbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbtActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add New Products to Inventory");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(confirmbt, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(confirmbt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbtActionPerformed
        Customer_Class user = new Customer_Class();
        product p = new product();
        user.setUser_id(Integer.parseInt(NewJFrame.mypassword));
        user.setContact(NewJFrame.mypassword);
        user.setUname(NewJFrame.myusername);
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mma");
        String timing= sdf.format(cal.getTime()) ;
        user.setTime(timing);

        for (int i=0;i<NewJFrame.order.size();i++)
        {
            count=NewJFrame.dbClient2.view("abc/product_price").key(NewJFrame.order.get(i)).queryForInt();
            temp+=count* Integer.parseInt((String) NewJFrame.quantity.get(i));
            count1 = NewJFrame.dbClient2.view("abc/product_sell").key(NewJFrame.order.get(i)).queryForInt();
            count2 = NewJFrame.dbClient2.view("abc/product_quantity").key(NewJFrame.order.get(i)).queryForInt();
            count3 = NewJFrame.dbClient2.view("abc/product_id").key(NewJFrame.order.get(i)).queryForInt();
            dc = NewJFrame.dbClient2.view("abc/product_doc").key(NewJFrame.order.get(i)).queryForString();
            bc = NewJFrame.dbClient2.view("abc/product_rev").key(NewJFrame.order.get(i)).queryForString();
            
            p.setPid(count3);
            p.setPname((String) NewJFrame.order.get(i));
            p.setPrice(count);
            
            if(count2 < Integer.parseInt((String) NewJFrame.quantity.get(i)))
            {
                JOptionPane.showMessageDialog(null,"We don't have "+NewJFrame.quantity.get(i)+" "+NewJFrame.order.get(i)+" in our stock","Out of Stock Error" ,JOptionPane.ERROR_MESSAGE);
                continue;
            }
            else  
            {
                count2=count2-Integer.parseInt((String) NewJFrame.quantity.get(i));
            }
            count1=count1+Integer.parseInt((String) NewJFrame.quantity.get(i));
            p.setSold(count1);
            p.setQuantity(count2);
            Response response = NewJFrame.dbClient2.remove(dc,bc); 

            NewJFrame.dbClient2.save(p);
        }
        user.setBill(temp);
        NewJFrame.dbClient2.save(user);
        dispose();
        System.out.println(temp);
        NewJFrame.order.clear();
        NewJFrame.quantity.clear();
        NewJFrame logout = new NewJFrame();
        logout.setVisible(true);
    }//GEN-LAST:event_confirmbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        productadd ad = new productadd();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cname;
    private javax.swing.JButton confirmbt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
